export const GOOGLE_URL = 'https://google.com';
export const SKILL_HEADER = 'PROJECT AND CONSTRUCTION MANAGEMENT';
export const ACTION_HEADER = 'Want to build something amazing?';
export const GET_IN_TOUCH = 'GET IN TOUCH';
export const SIGNUP_HEADER = "Newsletter Signup";
export const SIGNUP = 'SIGNUP';
export const HEADER_H1_TEXT = 'PARTNER WITH KONSTRUCT';
export const HEADER_P_TEXT = 'An award-winning construction management firm';
export const SCROLL_DOWN = 'SCROLL DOWN';
export const OUR_STORY = 'OUR STORY'
export const WE = 'WE';
export const PLAN = 'PLAN';
export const MANAGE = 'MANAGE';
export const BUILD = 'BUILD';
export const TEXT_LOREM = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat.'
export const COMPANY = 'COMPANY'
export const HOME = 'HOME';
export const SERVICES = 'SERVICES';
export const ABOUT = 'ABOUT';
export const CONTACT_US = 'CONTACT US';
export const PROJECTS ='PROJECTS'
export const FAQ = 'FAQ';
export const TERMS = 'TERMS';
export const CAREERS = 'CAREERS';
export const BLOG = "BLOG";
export const PARTNERS = 'PARTNERS';
export const NEWS = 'NEWS';
export const LINKS = 'LINKS';
export const WORK = 'WORK';
export const CONTACT = 'CONTACT';
export const ADDRESS = '213 Baker Street Oriel City Kounty 7000 KNW, Kountry Name';
export const PHONE = '+23 994 233 4022';
export const EMAIL = 'info@konstruct.com';
export const OUR_CAPABILITIES = 'OUR CAPABILITIES';
export const ALL_SERVICES = 'ALL SERVICES';
export const KONSTRUCT = 'Konstruct'


