export const GET_POKEMONS_DETAILS_SUCCEEDED = "GET_POKEMONS_DETAILS_SUCCEEDED";
export const ACTION_GET_POKEMONS_DETAILS_SUCCEEDED = (payload) => ({
  type: GET_POKEMONS_DETAILS_SUCCEEDED,
  payload,
});

export const GET_POKEMONS_DETAILS_FAILED = "GET_POKEMONS_DETAILS_FAILED";
export const ACTION_GET_POKEMONS_DETAILS_FAILED = (error) => ({
  type: GET_POKEMONS_DETAILS_FAILED,
  error,
});

export const GET_POKEMONS_DETAILS_REQUESTED = "GET_POKEMONS_DETAILS_REQUESTED";
export const ACTION_GET_POKEMONS_DETAILS_REQUESTED = (payload) => ({
  type: GET_POKEMONS_DETAILS_REQUESTED,
  payload,
});
